runtime: python311
entrypoint: gunicorn -k uvicorn.workers.UvicornWorker app:app --workers 2 --timeout 300

env_variables:
  MAPBOX_TOKEN: "your_token_here"
  MAPBOX_PUBLIC_TOKEN: "your_public_token_here"
  MAPBOX_USERNAME: "your_username_here"
  MAX_UPLOAD_SIZE: "500"

handlers:
- url: /static
  static_dir: static
  expiration: "30d"
  
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

instance_class: F2

inbound_services:
- warmup

vpc_access_connector:
  name: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME
