[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python setup_environment.py"

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port $PORT --workers 2"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30
numReplicas = 1

[env]
PYTHON_VERSION = "3.11"
