apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: weather-visualization
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/weather-visualization
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
        env:
        - name: MAPBOX_TOKEN
          valueFrom:
            secretKeyRef:
              name: mapbox-secrets
              key: token
        - name: MAPBOX_PUBLIC_TOKEN
          valueFrom:
            secretKeyRef:
              name: mapbox-secrets
              key: public_token
        - name: MAPBOX_USERNAME
          valueFrom:
            secretKeyRef:
              name: mapbox-secrets
              key: username
        ports:
        - containerPort: 8080
